<Project Sdk="Microsoft.NET.Sdk">



  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>NetCraft.ModBuild</RootNamespace>

    <PackAsTool>true</PackAsTool>
    <ToolCommandName>ncm</ToolCommandName>
    <PackageId>NetCraft.ModBuild.Tools</PackageId>
    <Description>NetCraft mod development helper tools</Description>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\iconttf.ttf" LogicalName="iconttf.ttf" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Gui\ui.html" LogicalName="ui.html" />
    <EmbeddedResource Include="Gui\marked.min.js" LogicalName="marked.min.js" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="ICSharpCode.Decompiler" Version="11.1.0.9782" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.14.0" />
    <PackageReference Include="Photino.NET" Version="4.0.16" />
    <PackageReference Include="SixLabors.ImageSharp.Drawing" Version="2.1.5" />
    <PackageReference Include="Spectre.Console" Version="0.57.2" />
    <PackageReference Include="YamlDotNet" Version="18.1.0" />
  </ItemGroup>

</Project>
