using System.Globalization;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Emit;
using NetCraft.ModBuild.Core;
using NetCraft.ModBuild.Diagnostics;
//两个 Diagnostic 与两个 DiagnosticSeverity 都重名 本地这套起别名区分
using RoslynDiagnostic = Microsoft.CodeAnalysis.Diagnostic;
using ProjectDiagnostic = NetCraft.ModBuild.Diagnostics.Diagnostic;
using ProjectSeverity = NetCraft.ModBuild.Diagnostics.DiagnosticSeverity;

namespace NetCraft.ModBuild.Compile;

//Compiler 用 Roslyn 直接把项目编成模组程序集
//不再经过 dotnet build 与 MSBuild 工程 产物与诊断都自己出
public static class Compiler
{
    //GeneratedPath 程序集信息那棵虚拟树 它自己的诊断不往外报
    private const string GeneratedPath = "AssemblyInfo.g.cs";

    //Compile 编出模组程序集 返回是否成功
    //assemblyName 是产物名 target 是产物完整路径
    public static bool Compile(string root, NcProject project, string assemblyName, string target, out string error)
    {
        error = string.Empty;

        //先看要不要重编 比时间戳比整份装配便宜得多
        if (Incremental.IsUpToDate(target, Inputs(root, project)))
        {
            Console.WriteLine($"Up to date, {target}");
            return true;
        }

        var assembled = CompilationFactory.Create(root, CompileOptions.From(project, assemblyName), out error);
        if (assembled is null)
            return false;

        var compilation = AddAssemblyInfo(assembled, project, root, assemblyName);

        //编译诊断先看一遍 有错就不必再写文件
        var errors = compilation.GetDiagnostics()
            .Where(diagnostic => diagnostic.Severity == Microsoft.CodeAnalysis.DiagnosticSeverity.Error
                && diagnostic.Location.GetLineSpan().Path != GeneratedPath)
            .ToList();

        if (errors.Count > 0)
        {
            DiagnosticRenderer.Render(ToDiagnostics(errors, root));
            error = $"{errors.Count} compile error(s)";
            return false;
        }

        Console.WriteLine($"Compiling {assemblyName} with Roslyn");
        if (!Emit(compilation, project, root, target, out error))
            return false;

        Console.WriteLine($"Finished build, {target}");
        return true;
    }

    //Inputs 会影响这份产物的全部文件
    //少列一个就可能拿着过期的 dll 去开服 所以宁可多算几个
    private static List<string> Inputs(string root, NcProject project)
    {
        var inputs = new List<string>(CompilationFactory.Inputs(root))
        {
            project.Path,
            Path.Combine(root, ModProject.ManifestName),
        };

        //备齐的那几样也算输入 包换版本 内核换版本 包带的 targets 改过 产物就该重编
        inputs.AddRange(Files(root, ProjectLayout.Packages));
        inputs.AddRange(Files(root, ProjectLayout.Kernel));
        inputs.AddRange(Files(root, ProjectLayout.Targets));

        //Avalonia 那批资源也要盯 它们不打进产物之外的地方 变了没人会替我们重编
        inputs.AddRange(AvaloniaResources.Inputs(root, project.AvaloniaResources));

        var icon = ModProject.TryFind(root)?.IconPath;
        if (icon is not null)
            inputs.Add(icon);

        return inputs;
    }

    //Files 目录下的全部文件 目录不在就当空
    private static IEnumerable<string> Files(string root, string relative)
    {
        var directory = Path.Combine(root, relative);
        return Directory.Exists(directory)
            ? Directory.EnumerateFiles(directory, "*", SearchOption.AllDirectories)
            : [];
    }

    //AddAssemblyInfo 把程序集信息那棵树补上
    //SDK 原先自动生成的那些缺了会导致版本与目标框架信息不全
    private static Compilation AddAssemblyInfo(ProjectCompilation assembled, NcProject project, string root,
        string assemblyName)
    {
        var manifest = ModProject.TryFind(root);
        var version = manifest?.Version ?? string.Empty;
        var title = manifest?.DisplayName ?? assemblyName;

        var text = $"""
            // <auto-generated/>
            using System.Reflection;
            using System.Runtime.CompilerServices;
            using System.Runtime.Versioning;

            [assembly: AssemblyTitle("{Escape(title)}")]
            [assembly: AssemblyProduct("{Escape(title)}")]
            [assembly: AssemblyVersion("{AssemblyVersionOf(version)}")]
            [assembly: AssemblyFileVersion("{AssemblyVersionOf(version)}")]
            [assembly: AssemblyInformationalVersion("{Escape(version)}")]
            [assembly: TargetFramework("{TargetFramework()}", FrameworkDisplayName = ".NET")]
            {Friends(project)}
            """;

        var tree = CSharpSyntaxTree.ParseText(text, assembled.ParseOptions,
            path: GeneratedPath, encoding: Encoding.UTF8);
        return assembled.Compilation.AddSyntaxTrees(tree);
    }

    //Friends InternalsVisibleTo 那几行
    private static string Friends(NcProject project)
        => string.Join(Environment.NewLine, project.InternalsVisibleTo
            .Select(name => $"[assembly: InternalsVisibleTo(\"{Escape(name)}\")]"));

    //Emit 写出程序集与符号文件 先落临时文件 成功了再挪过去
    private static bool Emit(Compilation compilation, NcProject project, string root, string target, out string error)
    {
        error = string.Empty;
        var directory = Path.GetDirectoryName(target)!;
        var temporary = Path.Combine(directory, Path.GetFileName(target) + ".tmp");
        var symbols = Path.ChangeExtension(temporary, ".pdb");

        try
        {
            Directory.CreateDirectory(directory);
            using (var pe = File.Create(temporary))
            using (var pdb = File.Create(symbols))
            {
                var result = compilation.Emit(
                    pe,
                    pdb,
                    options: new EmitOptions(debugInformationFormat: DebugInformationFormat.PortablePdb),
                    manifestResources: Resources(root, project));

                if (!result.Success)
                {
                    DiagnosticRenderer.Render(ToDiagnostics(result.Diagnostics, root));
                    error = "emit failed";
                    return false;
                }
            }

            File.Move(temporary, target, overwrite: true);
            File.Move(symbols, Path.ChangeExtension(target, ".pdb"), overwrite: true);
            return true;
        }
        catch (IOException e)
        {
            error = $"cannot write {target}: {e.Message}";
            return false;
        }
        finally
        {
            Discard(temporary);
            Discard(symbols);
        }
    }

    //Resources 要嵌进程序集的资源
    //数据清单是加载器认模组的唯一依据 图标按清单指的来
    //第三方依赖也要带上 模组分发出去只有这一个 dll 加载器解析不到时会从内嵌资源里找
    //Avalonia 那批另打成一个包 avares:// 那条路只认它
    private static List<ResourceDescription> Resources(string root, NcProject project)
    {
        var resources = new List<ResourceDescription>();
        var seen = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

        //重名资源会让 emit 直接失败 同名只留先来的那个
        void Add(string name, Func<Stream> open)
        {
            if (seen.Add(name))
                resources.Add(new ResourceDescription(name, open, isPublic: true));
        }

        void AddFile(string name, string path) => Add(name, () => File.OpenRead(path));

        var manifest = Path.Combine(root, ModProject.ManifestName);
        if (File.Exists(manifest))
            AddFile(ModProject.ManifestName, manifest);

        var icon = ModProject.TryFind(root)?.IconPath;
        if (icon is not null && File.Exists(icon))
            AddFile(Path.GetFileName(icon), icon);

        foreach (var path in PackageResolver.Assemblies(root))
        {
            if (File.Exists(path))
                AddFile(Path.GetFileName(path), path);
        }

        if (project.AvaloniaResources.Count > 0)
        {
            var packed = AvaloniaResources.Pack(root, project.AvaloniaResources);
            if (packed is null)
                Console.WriteLine("warning: <AvaloniaResources> matched no file, nothing is packed");
            else
                Add(AvaloniaResources.ResourceName, () => new MemoryStream(packed, writable: false));
        }

        return resources;
    }

    //ToDiagnostics 把 Roslyn 的诊断换成项目那套 好与检查那边的输出长得一样
    private static List<ProjectDiagnostic> ToDiagnostics(IEnumerable<RoslynDiagnostic> diagnostics, string root)
    {
        var items = new List<ProjectDiagnostic>();
        foreach (var diagnostic in diagnostics)
        {
            var span = diagnostic.Location.GetLineSpan();
            var file = string.IsNullOrEmpty(span.Path)
                ? string.Empty
                : Path.GetRelativePath(root, span.Path).Replace('\\', '/');

            items.Add(new ProjectDiagnostic(
                ProjectSeverity.Error,
                diagnostic.Id,
                diagnostic.GetMessage(CultureInfo.InvariantCulture),
                file,
                span.StartLinePosition.Line + 1,
                span.StartLinePosition.Character + 1,
                Math.Max(1, diagnostic.Location.SourceSpan.Length),
                SourceLine(span.Path, span.StartLinePosition.Line + 1),
                string.Empty,
                diagnostic.Descriptor.HelpLinkUri,
                CompileAdvice.Text(diagnostic.Id).Select(Suggestion.Text).ToList()));
        }
        return items;
    }

    //SourceLine 取某一行源码 取不到就空着
    private static string SourceLine(string path, int line)
    {
        if (string.IsNullOrEmpty(path) || path == GeneratedPath)
            return string.Empty;

        try
        {
            var index = line - 1;
            var lines = File.ReadAllLines(path);
            return index >= 0 && index < lines.Length ? lines[index] : string.Empty;
        }
        catch (IOException)
        {
            return string.Empty;
        }
    }

    //AssemblyVersionOf 版本号换成四段式
    //1.2.3 补成 1.2.3.0 带后缀的只取前面数字那几段
    private static string AssemblyVersionOf(string version)
    {
        var parts = new List<string>();
        foreach (var part in version.Split('.', '-', '+'))
        {
            if (!int.TryParse(part, out _))
                break;

            parts.Add(part);
            if (parts.Count == 4)
                break;
        }

        while (parts.Count < 4)
            parts.Add("0");
        return string.Join('.', parts);
    }

    //TargetFramework 当前运行的目标框架名
    private static string TargetFramework()
    {
        const string marker = "Version=v";
        var name = AppContext.TargetFrameworkName ?? string.Empty;
        var index = name.IndexOf(marker, StringComparison.OrdinalIgnoreCase);
        return index < 0 ? "net10.0" : "net" + name[(index + marker.Length)..];
    }

    //Escape 特性参数里的双引号与反斜杠要转义 不然源码直接坏掉
    private static string Escape(string value)
        => value.Replace("\\", "\\\\").Replace("\"", "\\\"");

    //Discard 临时文件没用了就删掉
    private static void Discard(string path)
    {
        try
        {
            if (File.Exists(path))
                File.Delete(path);
        }
        catch (IOException)
        {
            //删不掉也不影响结果 下次覆盖
        }
    }
}
